# Generated by Django 2.0.2 on 2020-07-21 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commentary', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentary',
            options={'verbose_name': 'Comentario', 'verbose_name_plural': 'Comentarios'},
        ),
        migrations.AlterField(
            model_name='commentary',
            name='content',
            field=models.TextField(verbose_name='Opinión'),
        ),
        migrations.AlterField(
            model_name='commentary',
            name='score',
            field=models.PositiveIntegerField(verbose_name='Estrellas'),
        ),
    ]
