# Generated by Django 3.0.6 on 2020-07-23 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('establecimientos', '0004_establishment_id_user'),
        ('commentary', '0002_auto_20200721_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentary',
            name='id_establecimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='establecimientos.Establishment'),
        ),
        migrations.AddField(
            model_name='commentary',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='Nombre'),
        ),
    ]
