# Generated by Django 2.1 on 2020-07-22 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_auto_20200721_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='precio',
            field=models.CharField(max_length=15, verbose_name='Precio'),
        ),
    ]
