# Generated by Django 2.1 on 2020-07-22 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0004_auto_20200722_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='precio',
            field=models.CharField(max_length=255, verbose_name='Precio $'),
        ),
    ]
