# Generated by Django 3.0.6 on 2020-07-22 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('establecimientos', '0003_establishment_description'),
        ('producto', '0006_auto_20200722_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='id_establishment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='establecimientos.Establishment'),
        ),
    ]
