# Generated by Django 3.0.6 on 2020-07-22 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('establecimientos', '0004_establishment_id_user'),
        ('producto', '0007_product_id_establishment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id_establishment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='establecimientos.Establishment', verbose_name='Establecimiento'),
        ),
    ]
