# Generated by Django 3.0.6 on 2020-07-21 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimientos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='establishment',
            options={'verbose_name': 'Establecimiento', 'verbose_name_plural': 'Establecimientos'},
        ),
        migrations.AlterField(
            model_name='establishment',
            name='direction',
            field=models.TextField(verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='establishment',
            name='image',
            field=models.ImageField(upload_to='image', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='establishment',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='establishment',
            name='schedule',
            field=models.CharField(max_length=255, verbose_name='Horario'),
        ),
    ]
